
# PostgreSQL via Docker
spring.datasource.url=jdbc:postgresql://localhost:5433/${DB_LOCAL_NAME}
spring.datasource.username=${DB_LOCAL_USERNAME}
spring.datasource.password=${DB_LOCAL_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver


spring.jpa.hibernate.ddl-auto=none
